# The URL the site will be built for
base_url = "/"

# The title of the site
title = "Q's Blog"

# The description of the site
description = "A CSer Personal Blog"

author = "Zhenyu Qi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Theme
theme = "radion"

# Whether to generate an Atom feed
generate_feeds = true
build_search_index = true

# Taxonomies
taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown]
render_emoji = true
bottom_footnotes = true
insert_anchor_links = "heading"

[markdown.highlighting]
style = "class"
dark_theme = "material-theme-palenight"
light_theme = "everforest-light"
error_on_missing_language = false

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true

[extra]
radion_title = "Q's Blog"
radion_menu = [
  { url = "/", name = "Home" },
  { url = "/cv", name = "CV" },
  { url = "/categories", name = "Categories" },
  { url = "/tags", name = "Tags" },
  { url = "/about", name = "About" },
]
github = "https://github.com/qzydustin/qzydustin.github.io"
codeblock = true
enable_search = true
theme = "toggle"
comments = false
